apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Delete, Recycle
  storageClassName: standard
  nfs:
    server: 192.168.49.1
    path: /Users/mohamed-ali.fathallah/Minikube/nfs-mount
  mountOptions:
    - nfsvers=3
    - udp