apiVersion: v1
kind: Service
metadata:
  name: notes-service
spec:
  selector:
    app: notes
    type: web
  # ports:
  # - nodePort: 30080
  #   port: 80
  #   targetPort: 80
  # type: NodePort
  ports:  
    - port: 80
      targetPort: 80
  type: LoadBalancer