apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: my-image
          volumeMounts:
            - mountPath: /path/in/container
              name: my-persistant-volume
      volumes:
        - name: my-persistant-volume
          persistentVolumeClaim:
            claimName: host-pvc