apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: my-empty-dir-volume
      mountPath: /var/empty-dir
  volumes:
  - name: my-empty-dir-volume
    emptyDir: {}
